(package "flymake-elsa"
         "0.1.0"
         "Flymake integration for Elsa")

(website-url "https://github.com/flymake/flymake-elsa")
(keywords "lisp" "elsa")

(package-file "flymake-elsa.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "flymake-easy")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
